# https://starship.rs/config

[package]
disabled = true

[custom.haskell]
disabled = true # Really slow
command = "echo \"λ \"(stack ghc --no-install-ghc -- --numeric-version)"
description = "GHC veresion via stack"
files = ["stack.yaml"]
format = "via [$symbol($output )]($style) "
style = "bold red"

[custom.tab]
description = "The current tab in the tab terminal multiplexer"
command = "tab --starship"
when = "tab --starship"
shell = ["sh"]
format = "[$output]($style) "
style = "bold blue"

[nix_shell]
disabled = false
use_name = true
impure_msg = "impure"
pure_msg = "pure"
symbol = "❄️ "
