#!/bin/sh

trap 'rm -f "$TMPFILE"' EXIT

TMPFILE=$(coreutils --coreutils-prog=mktemp "kitty-fuzzy.XXXXXXXXXX.json" --tmpdir=/tmp)

kitty @ ls | jq ".[] | select( .platform_window_id | contains($WINDOWID) ) | .tabs | .[] | .title | select(contains(\"fuzzy\") | not)" | tr -d "\"" > "$TMPFILE"

SELECTED=$(cat "$TMPFILE" | fzf --layout=reverse)

if [ -n "$SELECTED" ]; then
  kitty @ focus-window --match title:"$SELECTED"
fi
