# Path to your oh-my-zsh installation.
export ZSH="${HOME}/.oh-my-zsh"

# Theme & theme related attributes
ZSH_THEME="spaceship"
SPACESHIP_GOLANG_SHOW=false
SPACESHIP_CHAR_SYMBOL="|> "
SPACESHIP_TIME_SHOW=true
SPACESHIP_USER_SHOW=true
SPACESHIP_PACKAGE_SHOW=false

# Plugins, use wisely as to many will slow down shell startup
plugins=(vi-mode history-substring-search)

# Reload for plugins & theme
source $ZSH/oh-my-zsh.sh

# Kitty
alias replenysh-session='${KITTY_SESSIONS}/replenysh-session.sh'
alias elm-language-server-session='${KITTY_SESSIONS}/elm-language-server-session.sh'
alias bs-elm-session='${KITTY_SESSIONS}/bs-elm-session.sh'

# NVM
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" # This loads nvm
# place this after nvm initialization!

autoload -U add-zsh-hook
load-nvmrc() {
  local node_version="$(nvm version)"
  local nvmrc_path="$(nvm_find_nvmrc)"

  if [ -n "$nvmrc_path" ]; then
    local nvmrc_node_version=$(nvm version "$(cat "${nvmrc_path}")")

    if [ "$nvmrc_node_version" != "N/A" ] && [ "$nvmrc_node_version" != "$node_version" ]; then
      nvm use
    fi
  elif [ "$node_version" != "$(nvm version default)" ]; then
    echo "Reverting to nvm default version"
    nvm use default
  fi
}
add-zsh-hook chpwd load-nvmrc
load-nvmrc

# Path to custom helpers
source $HOME/scripts/helpers.sh

# Alias git to hub
eval "$(hub alias -s)"

# Search History
bindkey "^[[A" history-substring-search-up
bindkey "^[[B" history-substring-search-down
bindkey "^P" history-beginning-search-backward
bindkey "^N" history-beginning-search-forward

# Set language
export LANG=en_US.UTF-8

# Set Editor
export EDITOR=nvim
alias nvim_install='nvim +PlugInstall +UpdateRemotePlugins +qa'

# Set TERM colors
export TERM=xterm-256color

# Aliases
alias icloud='~/Library/Mobile\ Documents/com~apple~CloudDocs'
alias trash="rmtrash"
alias zshreload="source ~/.zshenv && source ~/.zshrc"

# Fuzzy Finder
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# OPAM configuration -- Probably should remove
. /Users/jaredramirez/.opam/opam-init/init.zsh > /dev/null 2> /dev/null || true
